#!/usr/bin/env php
<?php
	/* Copyright (C) by Hugo Leisink <hugo@leisink.net>
	 * This file is part of the Banshee PHP framework
	 * https://gitlab.com/hsleisink/banshee/
	 *
	 * Licensed under The MIT License
	 */

	error_reporting(E_ALL & ~E_NOTICE);
	chdir(__DIR__);

	require "libraries/banshee/core/banshee.php";
	require "libraries/banshee/core/security.php";
	require "libraries/helpers/console.php";
	require "libraries/helpers/layout_general.php";
	require "libraries/helpers/layout_create.php";
	require "libraries/helpers/layout_delete.php";
	require "libraries/helpers/layout_import.php";

	/* Show help
	 */
	function show_help() {
		printf("Usage: %s activate|create|delete|import <options>\n", $GLOBALS["argv"][0]);
		printf("   activate <layout name>\n");
		printf("   create <layout name>\n");
		printf("   delete <layout name>\n");
		printf("   import <other banshee directory> <layout name>\n");
	}

	/* Start
	 */
	if (is_dir("settings") == false) {
		exit("Not inside a Banshee website directory.\n");
	}

	if (count($argv) < 3) {
		show_help();
		exit;
	}

	switch ($argv[1]) {
		case "activate":
			$layout = "views/banshee/layout_".$argv[2].".xslt";
			if (file_exists($layout) == false) {
				print "Layout does not exist.\n";
			} else {
				print "Activating layout.\n";
				activate_layout($argv[2]);
			}
			break;
		case "create":
			create_layout($argv[2]);
			break;
		case "delete":
			delete_layout($argv[2]);
			break;
		case "import":
			if (count($argv) < 4) {
				show_help();
				exit;
			}

			$banshee_dir = rtrim($argv[2], "/");
			if ($banshee_dir == "") {
				show_help();
				exit;
			}

			$checks = array(
				"libraries/banshee.php",
				"libraries/core/banshee.php",
				"libraries/banshee/core/banshee.php");
			$banshee_found = false;

			foreach ($checks as $check) {
				if (file_exists($banshee_dir."/".$check) == false) {
					$banshee_found = true;
					break;
				}
			}

			if ($banshee_found == false) {
				print "No Banshee installation detected in directory.\n";
				exit;
			}

			import_layout($banshee_dir, $argv[3]);
			break;
		default:
			show_help();
	}
?>
