#!/usr/bin/env php
<?php
	/* Copyright (C) by Hugo Leisink <hugo@leisink.net>
	 * This file is part of the Banshee PHP framework
	 * https://gitlab.com/hsleisink/banshee/
	 *
	 * Licensed under The MIT License
	 */

	error_reporting(E_ALL & ~E_NOTICE);
	chdir(__DIR__);

	require "libraries/banshee/core/banshee.php";
	require "libraries/banshee/core/security.php";
	require "libraries/helpers/console.php";
	require "libraries/helpers/module_list.php";
	require "libraries/helpers/module_create.php";
	require "libraries/helpers/module_delete.php";
	require "libraries/helpers/module_import.php";
	require "libraries/helpers/module_rename.php";

	/* Show help
	 */
	function show_help() {
		printf("Usage: %s create|delete|import|rename <options>\n", $GLOBALS["argv"][0]);
		printf("   create public|private <module name> [tm|sf|db|api]\n");
		printf("      tm: create a TableManager module.\n");
		printf("      sf: create a SplitForm module.\n");
		printf("      db: create a CRUD module.\n");
		printf("      api: create an API module.\n");
		printf("   delete <module name>\n");
		printf("   import <other banshee directory> <module name>\n");
		printf("   rename <module name> <new module name>\n");
	}

	/* Start
	 */
	switch ($argv[1] ?? null) {
		case "create":
			if (count($argv) < 4) {
				show_help();
				exit;
			} else if (in_array($argv[2], array("public", "private")) == false) {
				show_help();
				exit;
			}

			create_module($argv[2], $argv[3], $argv[4] ?? null);
			break;
		case "delete":
			if (count($argv) < 3) {
				show_modules($banshee_modules, $argv[0]);
				exit;
			}

		    $modules = $argv;
		    array_shift($modules);
		    array_shift($modules);

			$delete = array();
			foreach ($modules as $module) {
				if (isset($banshee_modules[$module])) {
					array_push($delete, $banshee_modules[$module]);
				} else if (module_exists($module)) {
					$delete[$module] = array("pages" => array($module));
				} else {
					printf("Module '%s' does not exist or is not active.\n", $module);
				}
			}

			$db = @new \Banshee\Database\MySQLi_connection(DB_HOSTNAME, DB_DATABASE, DB_USERNAME, DB_PASSWORD);

			delete_modules($delete, $db);
			break;
		case "import":
			if (count($argv) < 4) {
				show_help();
				exit;
			}

			$banshee_dir = rtrim($argv[2], "/");
			if ($banshee_dir == "") {
				show_help();
				exit;
			}

			$files = array(
				"libraries/banshee.php",
				"libraries/core/banshee.php",
				"libraries/banshee/core/banshee.php");
			$banshee_found = false;
			foreach ($files as $file) {
				if (file_exists($banshee_dir."/".$file)) {
					$banshee_found = true;
					break;
				}
			}

			if ($banshee_found == false) {
				print "No Banshee installation detected in directory.\n";
				exit;
			}

			module_import($banshee_dir, $argv[3]);
			break;
		case "rename":
			if (count($argv) < 4) {
				show_help();
				exit;
			}

			rename_module($argv[2], $argv[3]);
			break;
		default:
			show_help();
	}
?>
