<?php
	class dynamic_page_blocks extends Banshee\dynamic_blocks {
		protected $xslt_path = "views/demos";

		protected function xslt_generated($parameter = "") {
			$this->view->add_tag("content", $parameter);
		}

		protected function php_generated($parameter = null) {
			$result = "This line is generated by PHP.";

			if ($parameter !== null) {
				$result .= " Parameter: ".$parameter;
			}

			return $result;
		}
	}
?>
