#!/bin/bash

if [ "$1" = "" ]; then
	echo "Usage: $0 <version>"
	exit
fi

cd `dirname $0`/../public/js/webui
version=$1

echo "Downloading jQuery UI v${version}."
wget -qO jquery-ui.min.js http://code.jquery.com/ui/${version}/jquery-ui.min.js

if [ ! -s jquery-ui.min.js ]; then
	rm -f jquery-ui.min.js
	echo "Download error."
	exit
fi

mv -f jquery-ui.min.js jquery-ui.js

cd ../../css/webui

wget -qO jquery-ui.new.css https://code.jquery.com/ui/${version}/themes/base/jquery-ui.css

if [ ! -s jquery-ui.new.css ]; then
	rm -f jquery-ui.new.css
	echo "Download error."
	exit
fi

cat jquery-ui.new.css | sed 's/"images/"\/images\/jquery/' > jquery-ui.css

rm -f jquery-ui.new.css
